package dev.dertyp.dbus.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.validate
import java.io.File
import java.io.OutputStream

class DbusDocProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("dev.dertyp.dbus.annotations.DbusDoc")
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        if (symbols.isEmpty()) return emptyList()

        val anySourceFile = symbols.first().containingFile?.filePath ?: return emptyList()
        val projectRoot = findProjectRoot(File(anySourceFile))
        
        val docPath = options["dbus.doc.path"] ?: "docs"
        val docName = options["dbus.doc.name"] ?: "DBUS_API.md"
        
        val docsDir = if (docPath.startsWith("/")) File(docPath) else File(projectRoot, docPath)
        if (!docsDir.exists()) docsDir.mkdirs()
        val docFile = File(docsDir, docName)

        val modelsToDocument = mutableSetOf<KSClassDeclaration>()
        
        symbols.forEach { symbol ->
            symbol.getAllFunctions().forEach { func ->
                val fDoc = func.annotations.find { it.shortName.asString() == "DbusMethodDoc" }
                val returnsModel = fDoc?.arguments?.find { it.name?.asString() == "returnsModel" }?.value as? KSType
                if (returnsModel != null && returnsModel.declaration.simpleName.asString() != "Any") {
                    collectModels(returnsModel, modelsToDocument)
                }

                func.parameters.forEach { param ->
                    val type = param.type.resolve()
                    if (type.declaration.simpleName.asString() == "Map") {
                        val keyType = type.arguments.getOrNull(0)?.type?.resolve()
                        if (keyType?.declaration is KSClassDeclaration && (keyType.declaration as KSClassDeclaration).classKind == ClassKind.ENUM_CLASS) {
                            collectModels(keyType, modelsToDocument)
                        }
                    }
                }
            }
        }

        val documentedModelNames = modelsToDocument.map { it.simpleName.asString() }.toSet()

        docFile.outputStream().use { out ->
            out.writeLine("# Synara D-Bus API Documentation")
            out.writeLine("")
            out.writeLine("This document is automatically generated by the DbusDocProcessor KSP.")
            out.writeLine("")

            symbols.forEach { symbol ->
                generateDoc(out, symbol, documentedModelNames)
            }

            if (modelsToDocument.isNotEmpty()) {
                out.writeLine("---")
                out.writeLine("## Data Models")
                out.writeLine("")
                modelsToDocument.sortedBy { it.simpleName.asString() }.forEach { model ->
                    generateModelDoc(out, model, documentedModelNames)
                }
            }
        }

        return symbols.filterNot { it.validate() }
    }

    private fun collectModels(type: KSType, set: MutableSet<KSClassDeclaration>) {
        val decl = type.declaration
        if (decl is KSClassDeclaration && (decl.classKind == ClassKind.CLASS || decl.classKind == ClassKind.ENUM_CLASS)) {
            val qName = decl.qualifiedName?.asString() ?: ""
            val isBuiltIn = qName.startsWith("kotlin.") ||
                    qName.startsWith("java.") ||
                    qName.startsWith("dev.dertyp.Platform")

            if (!isBuiltIn && !set.any { it.qualifiedName?.asString() == qName }) {
                set.add(decl)
                decl.getAllProperties().forEach { collectModels(it.type.resolve(), set) }
            }
        }
        type.arguments.forEach { argument -> argument.type?.resolve()?.let { collectModels(it, set) } }
    }

    private fun findProjectRoot(file: File): File {
        var current = file
        while (current.parentFile != null) {
            if (File(current, "settings.gradle.kts").exists() || File(current, "settings.gradle").exists()) {
                return current
            }
            current = current.parentFile
        }
        return file.parentFile ?: file
    }

    private fun generateDoc(out: OutputStream, symbol: KSClassDeclaration, documentedModels: Set<String>) {
        val name = symbol.simpleName.asString()
        val dbusInterface = symbol.annotations.find { it.shortName.asString() == "DBusInterfaceName" }
            ?.arguments?.firstOrNull()?.value as? String ?: name
            
        val docAnnotation = symbol.annotations.find { it.shortName.asString() == "DbusDoc" }
        val description = docAnnotation?.arguments?.firstOrNull()?.value as? String ?: ""

        out.writeLine("## Interface: `$dbusInterface`")
        if (description.isNotEmpty()) out.writeLine(description)
        out.writeLine("")
        
        out.writeLine("### Summary")
        out.writeLine("")
        out.writeLine("| Method | Parameters | Returns | Description |")
        out.writeLine("| :--- | :--- | :--- | :--- |")

        val functions = symbol.getAllFunctions().filter {
            it.simpleName.asString() !in listOf("<init>", "equals", "hashCode", "toString", "isRemote", "getObjectPath")
        }.toList()

        functions.forEach { func ->
            val fName = func.simpleName.asString()
            val fDoc = func.annotations.find { it.shortName.asString() == "DbusMethodDoc" }
            val desc = fDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
            
            val params = func.parameters.joinToString("<br>") { param ->
                val pName = param.name?.asString() ?: "arg"
                val pType = param.type.resolve().toTypeString(documentedModels)
                "`$pName` ($pType)"
            }.ifEmpty { "-" }

            val returnsModel = fDoc?.arguments?.find { it.name?.asString() == "returnsModel" }?.value as? KSType
            val returnsList = fDoc?.arguments?.find { it.name?.asString() == "returnsList" }?.value == true
            val retType = if (returnsModel != null && returnsModel.declaration.simpleName.asString() != "Any") {
                val modelStr = returnsModel.toTypeString(documentedModels)
                if (returnsList) "List<$modelStr>" else modelStr
            } else {
                func.returnType?.resolve()?.declaration?.simpleName?.asString() ?: "Unit"
            }

            out.writeLine("| [`$fName`](#${fName.lowercase()}) | $params | $retType | $desc |")
        }
        out.writeLine("")

        out.writeLine("### Methods")
        out.writeLine("")

        functions.forEach { func ->
            val fName = func.simpleName.asString()
            val fDoc = func.annotations.find { it.shortName.asString() == "DbusMethodDoc" }
            val desc = fDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
            
            out.writeLine("#### `$fName`")
            if (desc.isNotEmpty()) out.writeLine(desc)
            out.writeLine("")

            if (func.parameters.isNotEmpty()) {
                out.writeLine("**Parameters:**")
                out.writeLine("")
                out.writeLine("| Name | Type | Description |")
                out.writeLine("| :--- | :--- | :--- |")
                func.parameters.forEach { param ->
                    val pName = param.name?.asString() ?: "arg"
                    val type = param.type.resolve()
                    val pType = type.toTypeString(documentedModels)
                    val pDoc = param.annotations.find { it.shortName.asString() == "DbusParamDoc" }
                    val pDesc = pDoc?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
                    
                    val keyType = if (type.declaration.simpleName.asString() == "Map") type.arguments.getOrNull(0)?.type?.resolve() else null
                    val fullDesc = if (keyType?.declaration is KSClassDeclaration && (keyType.declaration as KSClassDeclaration).classKind == ClassKind.ENUM_CLASS) {
                        val keyName = keyType.declaration.simpleName.asString()
                        "$pDesc (Valid keys: [$keyName](#${keyName.lowercase()}))"
                    } else {
                        pDesc
                    }
                    
                    out.writeLine("| `$pName` | $pType | $fullDesc |")
                }
                out.writeLine("")
            }

            val exampleStr = fDoc?.arguments?.find { it.name?.asString() == "example" }?.value as? String ?: ""
            out.writeLine("**Example Usage:**")
            out.writeLine("```shell")
            out.writeLine(generateExample(dbusInterface, fName, func, fDoc, exampleStr))
            out.writeLine("```")
            out.writeLine("")
        }
    }

    private fun generateExample(dbusInterface: String, methodName: String, func: KSFunctionDeclaration, methodAnnotation: KSAnnotation?, customExample: String): String {
        if (customExample.startsWith("dbus-send") || customExample.startsWith("busctl")) {
            return customExample
        }

        val dest = "org.mpris.MediaPlayer2.synara"
        val path = "/dev/dertyp/synara"
        
        val args = customExample.ifEmpty {
            func.parameters.joinToString(" ") { param ->
                val type = param.type.resolve()
                val pType = type.declaration.simpleName.asString()
                val pDoc = param.annotations.find { it.shortName.asString() == "DbusParamDoc" }
                val pExample = pDoc?.arguments?.find { it.name?.asString() == "example" }?.value as? String ?: ""

                when (pType) {
                    "String" -> "string:\"${pExample.ifEmpty { "..." }}\""
                    "Int" -> "int32:${pExample.ifEmpty { "0" }}"
                    "Long" -> "int64:${pExample.ifEmpty { "0" }}"
                    "Boolean" -> "boolean:${pExample.ifEmpty { "true" }}"
                    "Map" -> {
                        val keyType = type.arguments.getOrNull(0)?.type?.resolve()
                        val valueType = type.arguments.getOrNull(1)?.type?.resolve()?.declaration?.simpleName?.asString() ?: "Variant"
                        
                        val dbusKeyType = toDbusTypeName(keyType?.declaration?.simpleName?.asString() ?: "String")
                        val dbusValueType = toDbusTypeName(valueType)
                        
                        val keyEx = if (keyType?.declaration is KSClassDeclaration && (keyType.declaration as KSClassDeclaration).classKind == ClassKind.ENUM_CLASS) {
                            (keyType.declaration as KSClassDeclaration).declarations
                                .filterIsInstance<KSClassDeclaration>()
                                .find { it.classKind == ClassKind.ENUM_ENTRY }
                                ?.simpleName?.asString() ?: "key"
                        } else {
                            "key"
                        }
                        
                        val valEx = if (dbusValueType == "variant") "variant:boolean:${pExample.ifEmpty { "true" }}" else "true"
                        "dict:$dbusKeyType:$dbusValueType:\"$keyEx\",$valEx"
                    }
                    else -> "string:\"...\""
                }
            }
        }

        val returnsModel = methodAnnotation?.arguments?.find { it.name?.asString() == "returnsModel" }?.value as? KSType
        val isJson = returnsModel != null && returnsModel.declaration.simpleName.asString() != "Any"
        
        val printReply = if (func.returnType?.resolve()?.declaration?.simpleName?.asString() != "Unit" || isJson) "--print-reply=literal " else ""
        val pipe = if (isJson) " | jq ." else ""
        
        return "dbus-send --session $printReply--dest=$dest $path $dbusInterface.$methodName $args$pipe"
    }

    private fun toDbusTypeName(kotlinType: String): String {
        return when (kotlinType) {
            "String" -> "string"
            "Int" -> "int32"
            "Long" -> "int64"
            "Boolean" -> "boolean"
            "Double" -> "double"
            "Byte" -> "byte"
            "Short" -> "int16"
            "Variant" -> "variant"
            else -> "string"
        }
    }

    private fun generateModelDoc(out: OutputStream, model: KSClassDeclaration, documentedModels: Set<String>) {
        val name = model.simpleName.asString()
        out.writeLine("### $name")
        out.writeLine("")
        
        if (model.classKind == ClassKind.ENUM_CLASS) {
            out.writeLine("| Value | Description |")
            out.writeLine("| :--- | :--- |")
            model.declarations.filterIsInstance<KSClassDeclaration>()
                .filter { it.classKind == ClassKind.ENUM_ENTRY }
                .forEach { entry ->
                    val fDoc = entry.annotations.find { it.shortName.asString() == "DbusFieldDoc" }
                    val fDesc = fDoc?.arguments?.firstOrNull()?.value as? String ?: ""
                    out.writeLine("| `${entry.simpleName.asString()}` | $fDesc |")
                }
        } else {
            out.writeLine("| Field | Type | Description |")
            out.writeLine("| :--- | :--- | :--- |")
            model.getAllProperties().forEach { prop ->
                val pName = prop.simpleName.asString()
                val pType = prop.type.resolve().toTypeString(documentedModels)
                val fDoc = prop.annotations.find { it.shortName.asString() == "DbusFieldDoc" }
                val fDesc = fDoc?.arguments?.firstOrNull()?.value as? String ?: ""
                out.writeLine("| `$pName` | $pType | $fDesc |")
            }
        }
        out.writeLine("")
    }

    private fun KSType.toTypeString(documentedModels: Set<String>): String {
        val name = declaration.simpleName.asString()
        val nullability = if (isMarkedNullable) "?" else ""

        val displayName = if (name in documentedModels) {
            "[$name](#${name.lowercase()})"
        } else {
            name
        }

        if (arguments.isEmpty()) return "$displayName$nullability"
        val args = arguments.joinToString(", ") { it.type?.resolve()?.toTypeString(documentedModels) ?: "Any" }
        return "$displayName<$args>$nullability"
    }

    private fun OutputStream.writeLine(str: String) = this.write((str + "\n").toByteArray())
}

class DbusDocProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment) = 
        DbusDocProcessor(environment.codeGenerator, environment.logger, environment.options)
}
