
import java.awt.RenderingHints
import java.awt.image.BufferedImage
import javax.imageio.IIOImage
import javax.imageio.ImageIO

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.jetbrains.compose)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlinx.rpc)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.sqldelight)
}

val prerelease = true
val major = 1
val minor = 0
val patch = 0
val buildMajor = 0
val buildMinor = 0
val buildPatch = 5

fun getVersionName(): String {
    return "$major.$minor.$patch${if (prerelease) "-prerelease$buildMajor.$buildMinor.$buildPatch" else ""}"
}

version = getVersionName()

kotlin {
    jvm()

    sourceSets {
        commonMain {
            dependencies {
                implementation(project(":tray"))
                implementation(project(":common-rpc"))

                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.voyager.navigator)
                implementation(libs.voyager.screenmodel)
                implementation(libs.voyager.transitions)
                implementation(libs.voyager.koin)
                implementation(libs.koin.core)
                implementation(libs.koin.compose)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.kotlinx.json)
                implementation(libs.ktor.serialization.kotlinx.cbor)
                implementation(libs.kotlinx.rpc.krpc.serialization.cbor)
                implementation(libs.ktor.client.websockets)
                
                // Persistence
                implementation(libs.multiplatform.settings.no.arg)
                implementation(libs.multiplatform.settings.serialization)
                implementation(libs.kaml)
                implementation(libs.kotlinx.serialization.cbor)
                implementation(libs.kotlinx.serialization.protobuf)
                implementation(libs.okio)
                implementation(libs.sqldelight.runtime)
                implementation(libs.sqldelight.coroutines.extensions)

                // Compose Resources
                implementation(libs.runtime)
                implementation(libs.foundation)
                implementation(libs.material3)
                implementation(libs.material.icons.extended)
                implementation(libs.components.resources)
                implementation(libs.ui.tooling.preview)

                // Coil
                implementation(libs.coil.compose)
                implementation(libs.coil.network.ktor3)
                
                // KMPalette
                implementation(libs.kmpalette.core)
                implementation(libs.kmpalette.androidx.palette)
            }

            kotlin.srcDir(
                tasks.register("generateBuildConfig") {
                    val outputDir = layout.buildDirectory.dir("generated/buildConfig/kotlin/main")
                    outputs.dir(outputDir)
                    doLast {
                        val configFile = outputDir.get().file("dev/dertyp/synara/BuildConfig.kt").asFile
                        configFile.parentFile.mkdirs()
                        configFile.writeText(
                            """
                            package dev.dertyp.synara
        
                            /*
                             * This file is generated by the build system.
                             * IS_DEBUG is true for 'run' and local builds, false for packaging/release.
                             */
                            object BuildConfig {
                                const val IS_DEBUG = ${gradle.startParameter.taskNames.none { 
                                    it.contains("package", ignoreCase = true) || 
                                    it.contains("release", ignoreCase = true) ||
                                    it.contains("createDistributable", ignoreCase = true)
                                }}
                                const val VERSION = "${getVersionName()}"
                            }
                            """.trimIndent()
                        )
                    }
                }
            )
        }
        
        jvmMain {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.ktor.client.cio)
                implementation(libs.kotlinx.coroutines.swing)

                // Audio (LWJGL OpenAL + FLAC decoding)
                implementation(libs.lwjgl)
                implementation(libs.lwjgl.openal)
                implementation(libs.lwjgl.stb)
                implementation(libs.jflac)
                
                implementation(libs.sqldelight.sqlite.driver)

                // D-Bus (MPRIS)
                implementation(libs.dbus.java.core)
                implementation(libs.dbus.java.transport.native.unixsocket)
                implementation(libs.zstd)
                implementation(libs.mediasession.kt)
                implementation(libs.jna)

                // Add natives for all desktop platforms
                val platforms = listOf("linux", "windows", "macos", "macos-arm64")
                platforms.forEach { platform ->
                    runtimeOnly("org.lwjgl:lwjgl::natives-$platform")
                    runtimeOnly("org.lwjgl:lwjgl-openal::natives-$platform")
                    runtimeOnly("org.lwjgl:lwjgl-stb::natives-$platform")
                }
            }
        }
    }

    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }
}

sqldelight {
    databases {
        create("SynaraDatabase") {
            packageName.set("dev.dertyp.synara.db")
        }
    }
}

compose.resources {
    publicResClass = true
}

configurations.all {
    exclude(group = "org.jetbrains.compose.material", module = "material-desktop")
}

tasks.register("generateIcons") {
    val inputIcon = file("src/commonMain/resources/icon.png")
    val outputDir = layout.buildDirectory.dir("generated/icons")
    inputs.file(inputIcon)
    outputs.dir(outputDir)
    
    doLast {
        if (!outputDir.get().asFile.exists()) outputDir.get().asFile.mkdirs()
        
        val originalImage = ImageIO.read(inputIcon)
        val sizes = listOf(16, 32, 48, 64, 128, 256, 512, 1024)
        
        fun createResizedImage(size: Int): BufferedImage {
            val resized = BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB)
            val g = resized.createGraphics()
            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC)
            g.drawImage(originalImage, 0, 0, size, size, null)
            g.dispose()
            return resized
        }

        val icoFile = outputDir.get().file("icon.ico").asFile
        try {
            val icoWriter = ImageIO.getImageWritersByFormatName("ICO").next()
            ImageIO.createImageOutputStream(icoFile).use { ios ->
                icoWriter.output = ios
                icoWriter.prepareWriteSequence(null)
                sizes.filter { it <= 256 }.forEach { size ->
                    icoWriter.writeToSequence(IIOImage(createResizedImage(size), null, null), null)
                }
                icoWriter.endWriteSequence()
            }
        } catch (e: Exception) {
            logger.warn("Could not generate .ico file: ${e.message}")
        }

        val icnsFile = outputDir.get().file("icon.icns").asFile
        try {
            val icnsWriter = ImageIO.getImageWritersByFormatName("ICNS").next()
            ImageIO.createImageOutputStream(icnsFile).use { ios ->
                icnsWriter.output = ios
                icnsWriter.prepareWriteSequence(null)
                sizes.forEach { size ->
                    icnsWriter.writeToSequence(IIOImage(createResizedImage(size), null, null), null)
                }
                icnsWriter.endWriteSequence()
            }
        } catch (e: Exception) {
            logger.warn("Could not generate .icns file: ${e.message}")
        }
    }
}
